#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FeatureController.Features.Bar.Views.Index
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Index/Index.cshtml")]
    public partial class Index : System.Web.Mvc.WebViewPage<IEnumerable<FeatureController.Features.Bar.ViewModels.BarListViewModel>>
    {
        public Index()
        {
        }
        public override void Execute()
        {
WriteLiteral("<table>\r\n    <thead>\r\n        <tr>\r\n            <th>");

            
            #line 6 "..\..\Views\Index\Index.cshtml"
           Write(Html.DisplayNameFor(x => x.MyBar));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n            <th>");

            
            #line 7 "..\..\Views\Index\Index.cshtml"
           Write(Html.DisplayNameFor(x => x.MyF00));

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n            <th>Details</th>\r\n        </tr>\r\n    </thead>\r\n    <tbody>\r\n");

            
            #line 12 "..\..\Views\Index\Index.cshtml"
        
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Index\Index.cshtml"
         foreach (var m in Model)
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n                <td>");

            
            #line 15 "..\..\Views\Index\Index.cshtml"
               Write(Html.DisplayFor(_ => m.MyBar));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 16 "..\..\Views\Index\Index.cshtml"
               Write(Html.DisplayFor(_ => m.MyF00));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");

            
            #line 17 "..\..\Views\Index\Index.cshtml"
               Write(Html.ActionLink("Edit", "Edit", new { id = m.MyF00 }));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n            </tr>\r\n");

            
            #line 19 "..\..\Views\Index\Index.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n</table>\r\n");

        }
    }
}
#pragma warning restore 1591
